### ISSUE TITLE
Release todo

### ISSUE THREAD

**Issue by samuelpowell** [Gowerlabs/lumomat#3]
Prior to release:

- [x] Confirm https://github.com/fNIRS/snirf/issues/107
- [x] Confirm https://github.com/fNIRS/snirf/issues/108
- [x] Add manual channel order tests in canonical enumeration, NIRS, and SNIRF outputs (including reordered SNIRF for MNE)
- [x] Validate NIRS and SNIRF stimulus output formats (requires new sample data)
- [x] Review all source TODO items
- [x] Review all function documentation headers and correlate with README
- [x] Add versioning within the repository for debug
- [ ] ~Finalise decision on grouping of of multiple datasets from hyper-scanning (e.g. groups hierarchy)~ (issue to be opened)
- [x] Check optode discrepancy ('0' vs '1' based detectors) in canonical, NIRS and SNIRF output
- [x] Reduce information text when loading LUMO and align with LUFR
- [x] Add layout validation, versioning, and version storage in canonical
- [ ] ~Add data source field in canonical, type and version~
- [ ] ~Extract recording information from lufr infoblock fields~
- [x] Reorganise and archive samples
- [x] Enforce landmarks on appropriate SNIRF styles
- [x] Check versioning limits on LUFR input
- [x] Check data norm warning on LUMO import, check data norm on LUFR
- [x] Add manual LUFR->NIRS tests
- [x] Optionalise SNIRF out of spec extended metadata

**Comment by samuelpowell** [comment]
Completed in #14
